apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: clhv3uesw-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/clhv3uesw-dotnet-basic-gitops